version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: actividad1-postgres
    environment:
      POSTGRES_DB: estaciones
      POSTGRES_USER: estaciones_user
      POSTGRES_PASSWORD: estaciones_pass
    ports:
      - "5432:5432"
    volumes:
      - estaciones-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U estaciones_user -d estaciones"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  estaciones-pgdata:
